server:
  port: 5000
spring:
  jpa:
    database: MySQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lim73OFXrkhAOEte
            clientSecret: b70d515ca934e8703801d5d8de74e45f5b3c8871
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
  provider:
    github:
      authorization-uri: https://github.com/login/oauth/authorize
      token-uri: httsp://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user