server:
  port: 5000
spring:
  jpa:
    database: MySQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liXCwBjIGkKTo905
            clientSecret: 375c32556c264a6ad83ca495684a079bd83d685e
            redirectUri: "https://{baseHost}{basePort}{basePath}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
  provider:
    github: 
      authorization-uri: https://github.com/login/oauth/authorize
      token-uri: httsp://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user