spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
datasource:
  url: jdbc:mysql://127.0.0.1:8080/ebdb
  username: ${rds.username}
  password: ${rds.password}