server:
  port: 5000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
datasource:
  url: jdbc:mysql://${rds.hostname}:${rds.port}/ebdb
  username: ${rds.username}
  password: ${rds.password}
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE